context:
  name: sillywalk
  version: "1.0.2"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 16cf27709e493b355567ff7a0f316324cf79b96bb7e7d723d99e0192f1441595

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv
    - uv-build

  run:
    - python >=${{ python_min }}
    - numpy
    - scikit-learn
    - narwhals
    - jinja2

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
      imports:
        - sillywalk

about:
  homepage: https://github.com/AnyBody-Research-Group/sillywalk
  summary: 'Library for maximum likelihood principal component analysis for AnyBody models'
  description: |
    sillywalk is a Python library for statistical modeling of human motion and
    anthropometric data with the AnyBody Modeling System. It implements Maximum
    Likelihood Principal Component Analysis (ML‑PCA) to learn compact,
    low‑dimensional models from datasets, predict missing or individualized
    signals from partial inputs, and export those predictions as AnyScript
    include files that plug directly into AnyBody models.

  license: MIT
  license_file: LICENSE
  documentation: https://github.com/AnyBody-Research-Group/sillywalk
  repository: https://github.com/AnyBody-Research-Group/sillywalk

extra:
  recipe-maintainers:
    - melund
